// <auto-generated />
using System;
using MVC_Hamburger.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Hamburger.Migrations
{
    [DbContext(typeof(HamburgerDbContext))]
    [Migration("20240513220156_InitDB2")]
    partial class InitDB2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.EkstraMalzeme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KategoriID");

                    b.ToTable("EkstraMalzemeler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "ketçap",
                            Fiyat = 20m,
                            KategoriID = 1
                        },
                        new
                        {
                            ID = 2,
                            Ad = "mayonez",
                            Fiyat = 20m,
                            KategoriID = 2
                        },
                        new
                        {
                            ID = 3,
                            Ad = "Sos İstemiyorum",
                            Fiyat = 0m,
                            KategoriID = 3
                        });
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriID = 1,
                            KategoriAdi = "İçecek"
                        },
                        new
                        {
                            KategoriID = 2,
                            KategoriAdi = "Tatlı"
                        },
                        new
                        {
                            KategoriID = 3,
                            KategoriAdi = "Sos"
                        },
                        new
                        {
                            KategoriID = 4,
                            KategoriAdi = "Çıtır Lezzetler"
                        });
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("ID");

                    b.ToTable("Menuler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "hamburger",
                            Fiyat = 159m,
                            ResimYolu = "sfdsfa"
                        },
                        new
                        {
                            ID = 2,
                            Ad = "burger",
                            Fiyat = 169m,
                            ResimYolu = "sfdsfa"
                        });
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "82f13da9-dfdc-4cfd-a32e-0f5a413abbc1",
                            Name = "Yonetici",
                            NormalizedName = "YONETICI"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "22509e60-4e1d-4711-9fc2-236f7b107a03",
                            Name = "Musteri",
                            NormalizedName = "MUSTERI"
                        });
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Siparis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Boy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("money");

                    b.Property<int>("UyeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UyeID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.SiparisEkstraMalzeme", b =>
                {
                    b.Property<int>("EkstraMalzemeID")
                        .HasColumnType("int");

                    b.Property<int>("SiparisID")
                        .HasColumnType("int");

                    b.Property<int>("EkstraMalzemeAdedi")
                        .HasColumnType("int");

                    b.HasKey("EkstraMalzemeID", "SiparisID");

                    b.HasIndex("SiparisID");

                    b.ToTable("SiparisEkstraMalzemeler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.SiparisMenu", b =>
                {
                    b.Property<int>("SiparisID")
                        .HasColumnType("int");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<int>("MenuAdedi")
                        .HasColumnType("int");

                    b.HasKey("SiparisID", "MenuID");

                    b.HasIndex("MenuID");

                    b.ToTable("SiparisMenuler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Adres = "Istanbul",
                            ConcurrencyStamp = "3db0b96e-f976-4b97-a395-39d8ef7ff20a",
                            Email = "deniz@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DENIZ@ADMIN.COM",
                            NormalizedUserName = "DENIZ@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAyeFlXWdlJba0xpRXOkWWS4+r5Uy+d7xTtROudZQV9lv3RiElrgIZcFz31kZ1gj1A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2f08fdbb-42f3-4046-aadf-cc3412dfe8e1",
                            TwoFactorEnabled = false,
                            UserName = "deniz@admin.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Adres = "Istanbul",
                            ConcurrencyStamp = "84744600-3114-49b5-b671-508e4b32aceb",
                            Email = "cemre@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CEMRE@ADMIN.COM",
                            NormalizedUserName = "CEMRE@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8F9yFckIMY+v/NUmZFRTXUzuHgU7YL50kkDKpjamSvp+GQIaGoFzCBJKIYyYv+qg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3539b586-04a5-4521-a185-05698db23187",
                            TwoFactorEnabled = false,
                            UserName = "cemre@admin.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Adres = "Istanbul",
                            ConcurrencyStamp = "b1c0ee27-f5a0-4492-a3cf-c8da6a8c8320",
                            Email = "onur@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ONUR@ADMIN.COM",
                            NormalizedUserName = "ONUR@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOWjzubiYrL1ELhU6+EPD767GLIkKbxvAQ8kcVP/a8Rciyi8GvJkiy2ZUgMe8N7p6w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e79aa308-9ce0-42ba-8cc4-4cb812a5013e",
                            TwoFactorEnabled = false,
                            UserName = "onur@admin.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.EkstraMalzeme", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Kategori", "Kategori")
                        .WithMany("EkstraMalzemeler")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Siparis", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", "Uye")
                        .WithMany("Siparisler")
                        .HasForeignKey("UyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.SiparisEkstraMalzeme", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.EkstraMalzeme", "EkstraMalzeme")
                        .WithMany("SiparisEkstraMalzemeler")
                        .HasForeignKey("EkstraMalzemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Hamburger.Models.Concrete.Siparis", "Siparis")
                        .WithMany("SiparisEkstraMalzemeler")
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkstraMalzeme");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.SiparisMenu", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Menu", "Menu")
                        .WithMany("SiparisMenuler")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Hamburger.Models.Concrete.Siparis", "Siparis")
                        .WithMany("SiparisMenuler")
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.EkstraMalzeme", b =>
                {
                    b.Navigation("SiparisEkstraMalzemeler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Kategori", b =>
                {
                    b.Navigation("EkstraMalzemeler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Menu", b =>
                {
                    b.Navigation("SiparisMenuler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Siparis", b =>
                {
                    b.Navigation("SiparisEkstraMalzemeler");

                    b.Navigation("SiparisMenuler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Uye", b =>
                {
                    b.Navigation("Siparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
