// <auto-generated />
using System;
using MVC_Hamburger.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Hamburger.Migrations
{
    [DbContext(typeof(HamburgerDbContext))]
    [Migration("20240518150335_SiparisEkstraMalzeme")]
    partial class SiparisEkstraMalzeme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.EkstraMalzeme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KategoriID");

                    b.ToTable("EkstraMalzemeler");

                    b.HasData(
                        new
                        {
                            ID = 3,
                            Ad = "Sos İstemiyorum",
                            Fiyat = 0m,
                            KategoriID = 3
                        });
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriID = 1,
                            KategoriAdi = "İçecek"
                        },
                        new
                        {
                            KategoriID = 2,
                            KategoriAdi = "Tatlı"
                        },
                        new
                        {
                            KategoriID = 3,
                            KategoriAdi = "Sos"
                        },
                        new
                        {
                            KategoriID = 4,
                            KategoriAdi = "Çıtır Lezzetler"
                        });
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money");

                    b.Property<string>("Icerik")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("ResimYolu")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("ID");

                    b.ToTable("Menuler");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "hamburger",
                            Fiyat = 159m,
                            ResimYolu = "sfdsfa"
                        },
                        new
                        {
                            ID = 2,
                            Ad = "burger",
                            Fiyat = 169m,
                            ResimYolu = "sfdsfa"
                        });
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "26b33612-696f-44f7-ba77-19e532765d29",
                            Name = "Yonetici",
                            NormalizedName = "YONETICI"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "b59c5bfc-60b8-4470-a4ed-ec519bc36115",
                            Name = "Musteri",
                            NormalizedName = "MUSTERI"
                        });
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Siparis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Boy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuAdedi")
                        .HasColumnType("int");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("money");

                    b.Property<int>("UyeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("UyeID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.SiparisEkstraMalzeme", b =>
                {
                    b.Property<int>("SiparisEkstraMalzemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisEkstraMalzemeID"));

                    b.Property<int>("EkstraMalzemeAdedi")
                        .HasColumnType("int");

                    b.Property<int>("EkstraMalzemeID")
                        .HasColumnType("int");

                    b.Property<int>("SiparisID")
                        .HasColumnType("int");

                    b.HasKey("SiparisEkstraMalzemeID");

                    b.HasIndex("EkstraMalzemeID");

                    b.HasIndex("SiparisID");

                    b.ToTable("SiparisEkstraMalzemeler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Adres = "Istanbul",
                            ConcurrencyStamp = "992d841f-721d-434d-8487-5f4eb257a687",
                            Email = "deniz@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DENIZ@ADMIN.COM",
                            NormalizedUserName = "DENIZ@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKqK0puf6SkOghwzJedCqRV8AnK//z/90PmwTs348YgXAbZXVmwx6MWM80IW204AzA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "65dbeb81-a253-4c9f-87bf-43f815a04504",
                            TwoFactorEnabled = false,
                            UserName = "deniz@admin.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Adres = "Istanbul",
                            ConcurrencyStamp = "3f58f35e-dbf8-4e34-bfc4-dbdd48c9cf29",
                            Email = "cemre@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CEMRE@ADMIN.COM",
                            NormalizedUserName = "CEMRE@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPfpUSx65H2LSutx2sjRdOkhdu9H4t8AJlmHh0eezjGrKx38T8qCP0RUAxk5/WN+ng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b819edd-26ce-4d70-8ebc-44ea44816f12",
                            TwoFactorEnabled = false,
                            UserName = "cemre@admin.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Adres = "Istanbul",
                            ConcurrencyStamp = "e8d8677e-8517-4732-99cf-1bcbaa9fad0f",
                            Email = "onur@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ONUR@ADMIN.COM",
                            NormalizedUserName = "ONUR@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPH9AsSRU7Fv/uu+7PB3pLGTrlMB04gTvxxYCdYI55Guu7nF75dBuOgf1oqzmFEhHA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f857f0f-6563-4623-b204-87afe5ecfa7f",
                            TwoFactorEnabled = false,
                            UserName = "onur@admin.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.EkstraMalzeme", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Kategori", "Kategori")
                        .WithMany("EkstraMalzemeler")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Siparis", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Menu", "Menu")
                        .WithMany("Siparisler")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", "Uye")
                        .WithMany("Siparisler")
                        .HasForeignKey("UyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.SiparisEkstraMalzeme", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.EkstraMalzeme", "EkstraMalzeme")
                        .WithMany("SiparisEkstraMalzemeler")
                        .HasForeignKey("EkstraMalzemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Hamburger.Models.Concrete.Siparis", "Siparis")
                        .WithMany("SiparisEkstraMalzemeler")
                        .HasForeignKey("SiparisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkstraMalzeme");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MVC_Hamburger.Models.Concrete.Uye", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.EkstraMalzeme", b =>
                {
                    b.Navigation("SiparisEkstraMalzemeler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Kategori", b =>
                {
                    b.Navigation("EkstraMalzemeler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Menu", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Siparis", b =>
                {
                    b.Navigation("SiparisEkstraMalzemeler");
                });

            modelBuilder.Entity("MVC_Hamburger.Models.Concrete.Uye", b =>
                {
                    b.Navigation("Siparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
